services:
  # Database PostgreSQL
  - type: postgres
    name: condominio-db
    plan: free
    databaseName: condominio_db
    user: condominio_user

  # Backend Flask
  - type: web
    name: condominio-api
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python app.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: condominio-db
          property: connectionString
      - key: FLASK_ENV
        value: production